version: '3.8'

services:
  # Frontend - SvelteKit —Å Nginx
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - gateway
    environment:
      - VITE_API_URL=http://localhost:8080
    volumes:
      - logs:/var/log/nginx

  # API Gateway - Fiber
  gateway:
    build:
      context: ../gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - user-service
      - game-service
      - chat-service
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8081
      - USER_SERVICE_URL=http://user-service:8082
      - GAME_SERVICE_URL=http://game-service:8083
      - CHAT_SERVICE_URL=http://chat-service:8084
    volumes:
      - logs:/app/logs

  # Auth Service
  auth-service:
    build:
      context: ../services/auth
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=auth_db
      - JWT_SECRET=your-secret-key
    volumes:
      - logs:/app/logs

  # User Service
  user-service:
    build:
      context: ../services/user
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=user_db
    volumes:
      - logs:/app/logs

  # Game Service
  game-service:
    build:
      context: ../services/game
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=game_db
    volumes:
      - logs:/app/logs

  # Chat Service
  chat-service:
    build:
      context: ../services/chat
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - postgres
    environment:
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=chat_db
    volumes:
      - logs:/app/logs

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
      - POSTGRES_MULTIPLE_DATABASES=auth_db,user_db,game_db,chat_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
      - logs:/var/log/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  logs: 